# Generated by Django 4.2.21 on 2025-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_user_age_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
