# Generated by Django 4.2.21 on 2025-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_borrower_loan_loanpurposecategory_transactionlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='repayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'Mpesa'), ('bank', 'Bank Transfer')], default='cash', max_length=50),
        ),
    ]
