# Generated by Django 4.2.21 on 2025-07-30 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_remove_repayment_amount_paid_repayment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='reviewed_at',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
