# Generated by Django 4.2.21 on 2025-07-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loanapplication_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='name',
        ),
    ]
