# Generated by Django 4.2.21 on 2025-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_remove_loanapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
