# Generated by Django 4.2.21 on 2025-07-31 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_loanapplication_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='name',
        ),
        migrations.CreateModel(
            name='ReviewCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('officer', 'application')},
            },
        ),
    ]
