# Generated by Django 4.2.21 on 2025-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_loanapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
