# Generated by Django 4.2.21 on 2025-08-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ['-created_at'], 'verbose_name': 'Borrower', 'verbose_name_plural': 'Borrowers'},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
    ]
