# Generated by Django 4.2.21 on 2025-08-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_alter_borrower_options_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-application_date']},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddField(
            model_name='repayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
