# Generated by Django 4.2.21 on 2025-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_alter_loan_options_alter_repayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='PENDING', max_length=10),
        ),
    ]
