# Generated by Django 4.2.21 on 2025-08-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='national_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
