# Generated by Django 4.2.21 on 2025-08-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_remove_loanapplication_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='defaultrecord',
            options={'ordering': ['-marked_date']},
        ),
    ]
